import './globals.css'


export const metadata = {
  title: 'Farflix',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-indigo-950'>
        {children}
      </body>
    </html>
  )
}
