import Navbar from '@/components/Navbar'
import './globals.css'


export const metadata = {
  title: 'Farflix',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-slate-900 flex flex-col w-[100vw-1px]'>
        {<Navbar></Navbar>}
        {children}
      </body>
    </html>
  )
}
